# -*- coding: utf-8 -*-
"""250311.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rm5YdMOvzK9IMT5VT-giJO02JouurY2
"""

"""과제 1"""

prompt = ''

def get_radius(prompt) :
  r = int(input(prompt))
  return r

def get_circle_area(r) :
  area = 3.14 * r * r
  return area

print('넓이를 구하고자 하는 원의 반지름은? ', end = '')

r = get_radius(prompt)

area = get_circle_area(r)

print('반지름 ', r, '인 원의 넓이: ', '3.14 x', r, 'x', r, '=', area)

