# -*- coding: utf-8 -*-
"""250318.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GN2ibMl654_exzVDr8v24SPHdyrQjNAD
"""


def get_integer():
    money = int(input('동전으로 교환하고자 하는 금액은? '))
    return money  # money 값을 반환

def exchange(money):
    five_h = money // 500  # 500원 동전 개수
    money -= five_h * 500  # 500원 동전 금액 차감

    h = money // 100  # 100원 동전 개수
    money -= h * 100  # 100원 동전 금액 차감

    fif = money // 50  # 50원 동전 개수
    money -= fif * 50  # 50원 동전 금액 차감

    t = money // 10  # 10원 동전 개수
    money -= t * 10  # 10원 동전 금액 차감

    # 결과 출력
    print('500원 동전의 개수: ', five_h)
    print('100원 동전의 개수: ', h)
    print('50원 동전의 개수: ', fif)
    print('10원 동전의 개수: ', t)

# 사용자로부터 금액을 입력받고 교환을 시작
money = get_integer()
exchange(money)