# -*- coding: utf-8 -*-
"""250325.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sLLxch7JXOL1oO_DICAgAB4u4vqXfkl

과제
"""

def get_fixed_price(price) :
  total_price = price * (100 / (100 - dc))
  return total_price

dc = int(input('할인율은? '))

a_price = int(input('A 상품의 할인된 가격은? '))
a_total = int(get_fixed_price(a_price))

b_price = int(input('B 상품의 할인된 가격은? '))
b_total = int(get_fixed_price(b_price))

print('A 상품의 정가는', a_total, '원')
print('B 상품의 정가는', b_total, '원')
