# -*- coding: utf-8 -*-
"""250401.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1ug4lLI0d5WLZOqN4CMxcSqkwrLuvtB
"""

"""과제"""

def rep_char(length) :
  print('-' * length)
  print(hello)
  print(welcome)
  print('-' * length)

def draw_line_string() :
  name = input('Input his/her name: ')
  hello = ' Hello ' + name + '. '
  welcome = ' Welcome to Seoul. '
  return name, hello, welcome

name, hello, welcome = draw_line_string()

nstr = len(hello) if (len(hello) > len(welcome)) else len(welcome)

rep_char(nstr)